### ISSUE TITLE
dts code editor ends with an error 'No such device or address'

### ISSUE THREAD

**Issue by memory-hunter** [duckietown/duckietown-shell-commands#389]
```
 dts code editor

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy
INFO:dts:looking at /home/memoryhunter/.dt-shell/commands-multi/daffy

dts :  An updated version of the commands is available.
    :  
    :  Attempting auto-update.

dts :  Updating commands...

dts :  OK
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.1.1 path /home/memoryhunter/.local/lib/python3.10/site-packages

dts :  Traceback (most recent call last):
    :    File "/home/memoryhunter/.local/lib/python3.10/site-packages/dt_shell/main.py", line 40, in cli_main
    :      cli_main_()
    :    File "/home/memoryhunter/.local/lib/python3.10/site-packages/dt_shell/main.py", line 201, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python3.10/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/memoryhunter/.local/lib/python3.10/site-packages/dt_shell/cli.py", line 284, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/memoryhunter/.local/lib/python3.10/site-packages/dt_shell/dt_command_abs.py", line 41, in do_command
    :      cls.commands[word].do_command(cls.commands[word], shell, " ".join(parts[1:]))
    :    File "/home/memoryhunter/.local/lib/python3.10/site-packages/dt_shell/dt_command_abs.py", line 54, in do_command
    :      cls.command(shell, args)
    :    File "/home/memoryhunter/.dt-shell/commands-multi/daffy/code/editor/command.py", line 45, in command
    :      default=get_user_login(),
    :    File "/home/memoryhunter/.dt-shell/commands-multi/daffy/utils/misc_utils.py", line 80, in get_user_login
    :      user = os.getlogin()
    :  OSError: [Errno 6] No such device or address

dts :  To report a bug, please also include the contents of /home/memoryhunter/shell-debug-info.txt
```

The `shell-debug-info.txt`:

```
commands-version: daffy
dt-authentication-daffy: 0.1.16
dt-data-api-daffy: 1.2.0
duckietown-docker-utils-daffy: 6.1.1
duckietown-shell: 5.4.5
duckietown-shell-commands: 5.4.5
encodings:
  locale: UTF-8
  stderr: utf-8
  stdout: utf-8
python: 3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0]
```
